// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHRQ6iaV7NupaoN-GV9VevzBrJzrLlwEE',
    appId: '1:391297390970:web:bf6755f557cfdfccaf5ec3',
    messagingSenderId: '391297390970',
    projectId: 'anc-pnc-viste-calculation',
    authDomain: 'anc-pnc-viste-calculation.firebaseapp.com',
    storageBucket: 'anc-pnc-viste-calculation.firebasestorage.app',
    measurementId: 'G-CFSBVGGCR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA836feVxV3fRKcpcZNbFFoadKxNUUJmjU',
    appId: '1:391297390970:android:925c7b8d39c34843af5ec3',
    messagingSenderId: '391297390970',
    projectId: 'anc-pnc-viste-calculation',
    storageBucket: 'anc-pnc-viste-calculation.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWdGqQC4hwtgIQgNmxoNvhKxNoDd9Dbrc',
    appId: '1:391297390970:ios:34272a571c2fc059af5ec3',
    messagingSenderId: '391297390970',
    projectId: 'anc-pnc-viste-calculation',
    storageBucket: 'anc-pnc-viste-calculation.firebasestorage.app',
    iosBundleId: 'com.app.ancDateCalculator',
  );
}
